apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-frontend.fullname" . }}-config
  labels:
    {{- include "todo-frontend.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_API_BASE_URL: {{ .Values.config.apiBaseUrl | quote }}
  NEXT_PUBLIC_BASE_URL: {{ .Values.config.baseUrl | quote }}
  BACKEND_API_URL: {{ .Values.config.backendApiUrl | quote }}
