apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secrets
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
